---
driver:
  name: vagrant
  customize:
    memory: 512
    cpus: 1
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["private_network", {ip: "192.168.56.20"}]
  ssh:
    insert_key: false
    #username: root
    #password: centos

transport:
  name: speedy_ssh

provisioner:
  name: chef_solo
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  #always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[elastic-beats::install_journalbeat]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      filebeat:
        config:
          output.kafka:
            enabled: true
          tags: ['tk','test']
          fields:
            env: tk-dev
          fields_under_root: true

        prospector:
